GET http://localhost:3000/api/word_game?sentence=The dog jumped over the shipyard fence
Content-Type: application/json

{
  "longestWord": 8,
  "shortestWord": "the",
  "sum": 32
}

### Get totalPhonebill
POST http://localhost:3000/api/phonebill/total
Content-Type: application/json

{
    "bill": "call,sms,call"
}

### Get current prices
GET http://localhost:3000/api/phonebill/prices
Content-Type: application/json

### New prices
POST http://localhost:3000/api/phonebill/price
Content-Type: application/json

{
  "type": "call",
  "price": 2.85
}

### Check Enough Airtime
POST http://localhost:3000/api/enough
Content-Type: application/json

{
  "usage": "call,sms,call",
  "available": 54
}
